version: '3'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/home/zHUB
    ports:
      - '8002:8002'
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db_crm3'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql