version: '3.7'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/home/dhub
    ports:
      - '8002:8002'
    env_file:
      - ./.env.dev
  db:
    image: mysql:8.0
    volumes:
      - zhub_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'zhub'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    restart: always
volumes:
  zhub_data: