version: '3'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/home/zHub
    ports:
      - '8002:8002'
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'zhub'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    restart: always
    volumes:
      - mysql-django:/var/lib/mysql

volumes:
    mysql-django:
      external: false
